//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yayks
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerShippingAddress
    {
        public string Id { get; set; }
        public string AspNetUserId { get; set; }
        public bool IsDefault { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
