//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yayks
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string Id { get; set; }
        public string OrdersId { get; set; }
        public string ProductsId { get; set; }
        public int Quantity { get; set; }
        public string Remarks { get; set; }
        public decimal Amount { get; set; }
        public string OrderDetailsStatus { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ShippingAddressId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual CustomerShippingAddress CustomerShippingAddress { get; set; }
    }
}
